version: 2
jobs:
  checkout_code:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/codybrunner.me
    steps:
      - checkout
      - attach_workspace:
          at: ~/codybrunner.me
      - restore_cache:
          keys:
            - 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
            - 'yarn-cache-{{ .Branch }}'
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  test_and_report:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/codybrunner.me
    steps:
      - attach_workspace:
          at: ~/codybrunner.me
      - run: yarn install
      - run: yarn start test.coverage
      - run: yarn start reportCoverage
      - store_artifacts:
          path: ./coverage/clover.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./coverage/clover.xml
  build:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/codybrunner.me
    steps:
      - attach_workspace:
          at: ~/codybrunner.me
      - run: yarn install
      - run:
          name: yarn build
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID} SITE_DOMAIN=${SITE_DOMAIN} yarn ci_build
            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
              GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID} SITE_DOMAIN=${SITE_DOMAIN_BETA} yarn ci_build
            else
              echo "This failed miserably!"
            fi
      - persist_to_workspace:
          root: .
          paths: .
  deployment:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/codybrunner.me
    steps:
      - attach_workspace:
          at: ~/codybrunner.me
      - run: yarn install
      - run: sudo yarn global add now
      - deploy:
          name: Deploy & Alias.
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              url=$(now public -t ${NOW_TOKEN} -n=my-site --static 2>/dev/null)
              echo "Site deployed to ${url}."
              now -t ${NOW_TOKEN} alias $url codybrunner.me
              echo "${url} aliased to https://codybrunner.me"
            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
              url=$(now public -t ${NOW_TOKEN} -n=my-site --static 2>/dev/null)
              echo "Site deployed to ${url}."
              now -t ${NOW_TOKEN} alias $url codybrunner-beta
              echo "${url} aliased to https://codybrunner-beta.now.sh"
            else
              echo "This failed miserably!"
            fi
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - checkout_code
      - test_and_report:
          requires:
            - checkout_code
      - build:
          requires:
            - test_and_report
      - deployment:
          requires:
            - test_and_report
            - build
          filters:
            branches:
              only:
                - development
                - master
